### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "new_user",
  "email": "newuser12@test.com",
  "address": "142,alley station",
  "dateOfBirth": "1987-06-14",
  "registeredDate": "2023-06-01"
}

###