### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Sammy",
  "email": "sammy@test.com",
  "address": "98,pearl station",
  "dateOfBirth": "1989-01-14",
  "registeredDate": "2023-10-11"
}

###