### Updates an existing patient entity
PUT http://localhost:4000/patients/f1e2e252-66ac-4a4b-97e5-3b7ef0c89677
Content-Type: application/json

{

  "name": "Sammyupdatednameonly",
  "email": "sammy@test.com",
  "address": "98,pearl station",
  "dateOfBirth": "1989-01-14"

}

###